### ISSUE TITLE
Autodetect xclip/xsel

### ISSUE THREAD

**Issue by cdown** [cdown/clipmenu#1]
@milouse did this in a fork, these should be integrated back into mainline.

**Comment by milouse** [comment]
Hi!
I do not contact you yet because I'm testing my little modifications. To be honnest I thought the both version could live independantly (and thank you very much for having given the first pieces of the puzzle to the community). But yes, the idea of providing a quick detection mode to merge the two version sounds good. If I've time I'll try to clean my work tonight and push to you a pull request if it pleases you :)

**Comment by cdown** [comment]
Hey!

Sure thing, otherwise I can do it, I don't mind. :-)

Here is the code I was thinking (untested).

```
for selection in clipboard primary; do
    if type xsel >/dev/null 2>&1; then
        # current invocation
    else
        # xclip invocation
    fi
done
```

This does the `type` check twice, but I think it's not a big problem here and makes the logic obvious.

**Comment by milouse** [comment]
Not ready yet. I must do the same thing in the daemon script. To ease future evolution (? why not), I'll try to merge back clipmenud into clipmenu. I've a first attempt (not working, killing kitten!) in a separate branch (milouse@d0e4bd12d9). What do you think?

**Comment by cdown** [comment]
Will add some comments on the commit. Thanks!

**Comment by cdown** [comment]
The commit seems a little heavyweight, and seems a little buggy. Please make sure your commit maps to a single action :-)

**Comment by milouse** [comment]
New commits in my two branch. Things are now working for me. Are things better now?

**Comment by cdown** [comment]
The code, as it is in the two commits, has quite a bit of superfluous code that could be reduced more elegantly. For example, I think the feature support checks are quite roundabout. There are also still the blockers to inclusion I mentioned, and the commits don't map to single actions as requested :-(

For now, I will make the commits and credit you in the commit message when adding support for xclip. Thanks for nudging me to fix these. :-)
