### ISSUE TITLE
rofi quirk

### ISSUE THREAD

**Issue by biopsin** [cdown/clipmenu#10]
I use rofi as a replacement for dmenu and noticed if more then 8 clips in the list, clipmenu will start when called, selecting the 9th line.   Editing dmenu_lines=${CLIPMENU_LINES} solved the selector starting allways from first line.  Guess it's a tiny headsup for any rofi users:)
Thanks for a great clipboard alternative!

**Comment by cdown** [comment]
Didn't know about rofi, interesting. Let me take a look later today and see what can be done.

**Comment by cdown** [comment]
I think this is a bug (or just a difference in functionality?) in `rofi`. I repro this but I think it's just the way that rofi's version of `-l` works. I'll go ask the author.

**Comment by cdown** [comment]
Bug acked upstream. Seems it's a wontfix for the author, sadly.

**Comment by DaveDavenport** [comment]
Will be fixed, might take some time to avoid breakage.

**Comment by cdown** [comment]
Thanks @DaveDavenport!
