### ISSUE TITLE
Paste in place?

### ISSUE THREAD

**Issue by wpcarro** [cdown/clipmenu#105]
Is there a way to paste directly from `clipmenu` without first moving the selected item to my primary selection?

**Comment by GladOSkar** [comment]
I don't know how you use `clipmenu` but i just bound my hotkey to

`clipmenu && xdotool key --clearmodifiers ctrl+v`

**Comment by wpcarro** [comment]
@GladOSkar oh this is exactly what I need. I didn't know about `xdotool`. Thank you! I'm using i3, so I did:

```
bindsym Ctrl+Shift+v exec clipmenu && xdotool key --clearmodifiers ctrl+v
```
