### ISSUE TITLE
clipmenu not sorted from newest to oldest dmenu

### ISSUE THREAD

**Issue by kristoferus75** [cdown/clipmenu#107]
Hi !

dmenu output ist not sorted -> the last text copy  is not in the beginning of the dmenu list -> it is somewhere else or one the second side of the dmenu list  ! i use sway and arch linux ! 

kind regards kirstoferus75

**Comment by cdown** [comment]
Hi, sorry, but this isn't enough information. At a minimum show a clean run with `CM_DEBUG=1`, and a subsection of `ls -l` output for files which you don't believe are sorting correctly. Thanks.

**Comment by kristoferus75** [comment]
Hi ! ok i understand but i have now seen that if i copy and mark with the mouse a text it put more lines in dmenu -> marked text is "beginning of the dmenu list" but in dmenu are more lines like this:
beginning o / beginning of dme / etc -> and that not always on the first place of dmenu -> i can also make  a debug if nessacery ! 

And if i mark with the mouse doubleclick (a word) the last marked text is alway on the second place -> if there ar more text lines in dmenu and clipmenu  -> crazy !

kind regards

**Comment by cdown** [comment]
Sorry, I'm afraid I don't understand your description. Please provide the data requested above :-)

**Comment by kristoferus75** [comment]
The dmenu list look like this if i mark this text with the mouse left buttton "beginning of the dmenu list":

dmenu :
first copy text
beginning o
beginning of dme
beginning of dmenu list
beginn

could be the problem that i use xwayland ?

**Comment by cdown** [comment]
I have no idea. For anything outside of the environment that maintainers use (which is Linux, with real X), you're basically going to have to debug those issues yourself :-)

However, providing the above debug info will help.

**Comment by kristoferus75** [comment]
Hi ! if i kill all clipmenud proceses and i start DEBUG=1 clipmenud > clipmenworking.log 2>&1
it works perfect -> here the debug and also the sorting in dmenu ist correct ! i only start clipmenud in the sway config : exec clipmenud 

in the .profile : 
export CM_DEBUG=1

Why are there more than on process of clipdmenud ?

Thanks !

[clipmenworking.log](https://github.com/cdown/clipmenu/files/3133998/clipmenworking.log)

**Comment by kristoferus75** [comment]
ok i have now see that if i make i logout from sway and than a login there than two processes if clipmenud and thats i thing is the problem !

i have now write a service file :

```
[Unit]
Description=Clipmenu daemon

[Service]
ExecStart=/usr/bin/clipmenud
Restart=always
RestartSec=0
#Environment=DISPLAY=:0
#Environment=CM_SELECTIONS=clipboard

MemoryDenyWriteExecute=yes
NoNewPrivileges=yes
ProtectControlGroups=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=
RestrictRealtime=yes

[Install]
WantedBy=default.target
```
But than the clipboard doesnt work and i get this error:

```
Mai 01 10:33:10 HOME clipmenud[7024]: xsel: Can't open display: (null)
Mai 01 10:33:10 HOME clipmenud[7024]: : Inappropriate ioctl for device
Mai 01 10:33:10 HOME clipmenud[7024]: xsel: Can't open display: (null)
Mai 01 10:33:10 HOME clipmenud[7024]: : Inappropriate ioctl for device
Mai 01 10:33:10 HOME clipmenud[7024]: Can't open X display
```

**Comment by kristoferus75** [comment]
i use now this script :

```
#!/bin/bash
# Use ps and grep to check if the program is running
ps -ef | grep -v grep | grep clipmenud
# if it is not running, start it.
if [ $? -eq 1 ]
then
#echo "The program is not running"
/usr/bin/clipmenud &
else
  :
#echo "The program is still running."
fi

```

**Comment by cdown** [comment]
Thanks, that makes sense. I wonder if we should also have explicit locking in clipmenud.

**Comment by cdown** [comment]
d5f1edb9698d3f8f9394f5c2a781ab7f9cdf41ba will make this less likely. Thanks for taking a look. :)
