### ISSUE TITLE
Change font?

### ISSUE THREAD

**Issue by wpcarro** [cdown/clipmenu#111]
Hi. I'd like to increase the font-size and change the font of `clipmenu`. I searched `clipmenu --help` and the docs here, but cannot seem to find an answer.

I would assume it'd use the same font as `dmenu` or `dmenu_run`, but both of these have different fonts from `clipmenu`. Any idea why there is a divergence between the fonts `dmenu` and `dmenu_run` are using and the font `clipmenu` is using?

**Comment by kaihendry** [comment]
clipmenu feeds its args to dmenu. e.g. `clipmenu -fn courier`

**Comment by wpcarro** [comment]
Thanks, @kaihendry.

I'm still confused about the font it's currently using. Any ideas why `dmenu` or `dmenu_run` should have different fonts than `clipmenu`?

**Comment by cdown** [comment]
There's no reason it should be different, we don't feed anything unusual. Most likely you launch dmenu_run/dmenu with different arguments, for example in dwm, dwm's theme and font are automatically passed to dmenu.
