### ISSUE TITLE
Tricky clipmenu behavior with google slides

### ISSUE THREAD

**Issue by fikovnik** [cdown/clipmenu#113]
I'm sorry for rather a fuzzy title, but here is what is happening in Google slides.
If I select any item on the slide which contains text and have some other than default formatting and do C-C, C-P its formatting is reset to the default one. In order to preserve it I have to press C-C couple of times with some delays in between. Usually it take me two to four tries,

When I disable clipmenu, it works as expected.

Is there some workaround?

**Comment by cdown** [comment]
Or I wonder if we can detect fancy clips and not persist those... hmm.

**Comment by cdown** [comment]
Should be fixed in clipmenu 6.0.0, thanks!
