### ISSUE TITLE
Emacs integration?

### ISSUE THREAD

**Issue by wpcarro** [cdown/clipmenu#115]
Thanks for making this. I'd like to write an Emacs client for `clipmenu`. Is this something that already exists but I'm just missing?

I've tried other clipboard managers built for Emacs, but I prefer `clipmenu` over all other tools I've used. I no longer use `rofi` or `dmenu`, which is why I stopped using `clipmenu`.

**Comment by cdown** [comment]
Hi! Realistically speaking, I don't use emacs, so it would be something you'd have to make (and support) yourself. I also don't even really know what what would look like :-)

**Comment by wpcarro** [comment]
No worries. I fully expected to write and maintain the client. I wanted to check with you first to ensure that one didn't already exist of which I was unaware.

**Comment by wpcarro** [comment]
For anyone looking for an Emacs client for `clipmenu`, I wrote one:

https://github.com/wpcarro/ivy-clipmenu.el
