### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by DamienCassou** [cdown/clipmenu#118]
There have been a few commits after the most recent release (from November 2018). Is the code ready for a new one?

**Comment by cdown** [comment]
Yeah, I've been hoping to do some cleanup work before next release, but didn't get around to it. I'll put out a release soon, thanks for the poke.

**Comment by cdown** [comment]
All looks good, just want to give a few days for e89f4843bbc59bfb8fec2a026f0b129fa08ce170 to bake in testing.

**Comment by cdown** [comment]
6.0.0 is now released. Thanks for the prod!

**Comment by DamienCassou** [comment]
Thank you
