### ISSUE TITLE
Need to copy twice to paste in Rider

### ISSUE THREAD

**Issue by DamienCassou** [cdown/clipmenu#119]
The [Jetbrains Rider IDE](https://www.jetbrains.com/rider/) acts weird when using clipmenud. Here is how to reproduce:

1. start clipmenud
1. open rider
2. open gedit
3. write something with gedit, select it, and <kbd>Ctrl+c</kbd>
4. go to rider, type <kbd>Ctrl+v</kbd>

Expected: the copied text appears
Actual: nothing appears

1. Go back to gedit
2. press  <kbd>Ctrl+c</kbd> again on the same text
3. go to rider, type <kbd>Ctrl+v</kbd>, the text correctly appears

I always have to copy something twice for it to be pastable inside Rider. Pasting anywhere else works as expected. I haven't found any other application which acts the same.

If I kill clipmenud, pasting in Rider works perfectly fine.

Yes, this is weird.

**Comment by cdown** [comment]
At a guess, Rider tries to take ownership of the clipboard or something (although I didn't install it to test). The second copy works because it bypasses clipmenu because of duplicate detection.

If this guess is right, then I suppose running clipmenud with `CM_OWN_CLIPBOARD=0` works?

I'm wondering if we should go back and make this the default again.

**Comment by GladOSkar** [comment]
Yeah for me this problem started showing up again as well. Lots of web apps and quite a few applications seem to take ownership and require a second copy since the last time i updated

**Comment by DamienCassou** [comment]
> I suppose running clipmenud with CM_OWN_CLIPBOARD=0 works?

this works for me!

**Comment by cdown** [comment]
Release 6.0.0 has CM_OWN_CLIPBOARD=0 by default and a whole bunch of other fixes. Let me know if you still experience issues. Thanks for the report! :-)

**Comment by DamienCassou** [comment]
Thank you
