### ISSUE TITLE
Request: Support for fzf

### ISSUE THREAD

**Issue by saheratarch** [cdown/clipmenu#122]
clipmenu is a great program, but it doesn't support fzf out of the box. Do you think you can support it? Thanks

**Comment by cdown** [comment]
I believe 5110fed should make it work -- let me know if it doesn't. It will go out with the next release :-)

**Comment by saheratarch** [comment]
Thanks for the quick response. I did something like 5110fed in my own system and it worked perfectly. Thanks!
