### ISSUE TITLE
Alacritty shift-insert issue

### ISSUE THREAD

**Issue by Mental64** [cdown/clipmenu#132]
After selecting a clip with clipmenu, then trying to paste the clip in the terminal with shift-insert fails to produce the clip.

The first press of shift-insert produces no output, the second press of shift-insert produces "^[[2~" on the screen. Then it just repeats this pattern, no output, then "^{{2~".

The workaround is to change focus away from the terminal, then back again, it it works as expected.

Middle mouse button pastes just fine, but I'm so used to shift-insert.

Terminal is alacritty, and clipmenu is 5.6.0

**Comment by cdown** [comment]
`^[[2~` is the start of an escape sequence, which probably means your terminal is trying (and failing) for some reason to do bracketed paste or something similar.

I've just installed alacritty and shift-insert works fine immediately after selecting a paste, so this is almost certainly a problem in your environment. Please try with default alacritty settings.

**Comment by Mental64** [comment]
I tried xterm and it worked fine. I also force reinstalled alacritty and still no go.
I'll fool around some more to see why it's happening.

alacritty 0.4.3 on dwm

**Comment by Mental64** [comment]
I had noticed my cursor changes when losing focus to dmenu, but not regaining properly if that makes sense.

Short story, it appears to be a dmenu problem for me...

https://github.com/i3/i3/issues/3528

**Comment by Mental64** [comment]
dmenu issue
