### ISSUE TITLE
Slows down on extremely long lines

### ISSUE THREAD

**Issue by szabolcs-szilagyi** [cdown/clipmenu#14]
It's a great lightweight tool, but really slows down when copying a single line that is extremely long.
Would like to propose to cut the first `N` character of the [selection](https://github.com/cdown/clipmenu/blob/develop/clipmenu#L13):
```
    first_line=$(sed -n '/./{p;q}' "$file" | cut -c1-100)
```

**Comment by cdown** [comment]
"Slows down" in what way? Is the slowdown visible when dmenu is launched?

In theory, I'm not against this. I'm just curious where you're seeing the slowdown.

**Comment by szabolcs-szilagyi** [comment]
Yes, when dmenu tries to show the content. Dmenu opens up slowly and when it finally opens the movement in it becomes very slow reacting.
I regularly copy-paste extremely large documents that are a single line of string, containing about 38000 characters.

**Comment by cdown** [comment]
Thanks for the report, I've added this feature in 95b8cd5.
