### ISSUE TITLE
Clipmenu help conflicts with dmenu -h flag

### ISSUE THREAD

**Issue by samyak-jain** [cdown/clipmenu#142]
In clipmenu, help will be displayed when using --help or -h. As seen in the code here: https://github.com/cdown/clipmenu/blob/764984c98285fc9071bd296fadec64d81681d7ea/clipmenu#L14

However, if we are using dmenu's line height patch https://tools.suckless.org/dmenu/patches/line-height/, then it will conflict since it uses -h flag to determine the height.

Suggestion: The easiest way would be to simply remove getting help from -h as --help would work anyway. Let me know if there's a different way we can solve this issue.

**Comment by cdown** [comment]
Oh sure, that's fine then. I've just removed it.
