### ISSUE TITLE
clipmenud problem  copy a row from libreoffice table

### ISSUE THREAD

**Issue by kristoferus75** [cdown/clipmenu#143]
Hi !

I have an issue if i copy a for example 170 items a row from libreoffice table ! 

It takes a very long time that dmenu opens the clipboard !

If i clean the clipboard all work normally again 

can i optimize this ?

Thanks

regards

**Comment by cdown** [comment]
Can you please be more clear about what you mean by "items"? We already limit line length to 300 characters, so unless you have a crazy high CM_MAX_CLIPS, I'm not immediately seeing why this should happen.

**Comment by kristoferus75** [comment]
sorry itmes are only text like this:

192.168.1.1
192.168.1.2
192.168.1.3
etc 170 times

this is my script that i open if i want to paste something:

```
#!/bin/bash
export CM_LAUNCHER=dmenu
export CM_DIR=~/.cache
export CM_HISTLENGTH=90
export CM_MAX_CLIPS=100

case "$1" in
        show)
                /usr/bin/clipmenu -c -l 12 -p Clipboard: -i -fn Terminus:size=16 ;;
        clean)
                clipdel -d ".*" && systemctl --user restart clipmenud.service \
                && notify-send "Clipboard Content deleted" -u low \
                || notify-send "Errors occurred while Clean Up" ;;
esac

```

**Comment by kristoferus75** [comment]
hmm i dont know why but now it works without problem

**Comment by cdown** [comment]
Feel free to reopen if you have a repro case.
