### ISSUE TITLE
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)

### ISSUE THREAD

**Issue by amaxcz** [cdown/clipmenu#148]
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error

bugs.... running under wayland
clipmenu 6.2.0-1

WAYLAND_DISPLAY=wayland-0
XDG_SESSION_TYPE=wayland

**Comment by cdown** [comment]
There's no wayland support, clipmenu is X only.

**Comment by amaxcz** [comment]
RIP. 

for everyone - use gpaste. its works
