### ISSUE TITLE
Status and toggle command

### ISSUE THREAD

**Issue by AckslD** [cdown/clipmenu#151]
I've on my own setup extended `clipctl` to also have the commands:
* `status`: Whether disabled or enabled.
* `toggle`: Toggle between disabled and enabled.

It's currently a bit hacky but if you find this interesting and I can open a PR to add these commands and discuss how to do this in the best way.

**Comment by cdown** [comment]
I think `status` sounds fine, but what's the use case for `toggle`? :-)

**Comment by AckslD** [comment]
In my case I put an icon in my status bar showing it's status and I can either click on it or using a key-combination to toggle the status. This might be a specialised need though and a toggle command can easily be created if `status` exists.

**Comment by cdown** [comment]
Sounds reasonable, in which case I think both are fine. Feel free to send a PR :-)

**Comment by AckslD** [comment]
Cool, I might cleanup some things first and open a PR in the coming days :+1:

**Comment by AckslD** [comment]
@cdown See PR #152. Let me know what you think :)
