### ISSUE TITLE
Feature request - transfer options ( e.g. primary <=> clipboard )

### ISSUE THREAD

**Issue by wwalker** [cdown/clipmenu#154]
I am constantly selecting something in one application and pasting into another, only to paste something that I selected long ago.

I would like to have a settable config option for `clipmenud` to:

* when there is a new value in `clipboard` immediately copy in into `primary` also
* when there is a new value in `primary` immediately copy in into `clipboard` also

whether the above is 2 separate options, or one option, doesn't matter to me, I will always want both.

This could be written as a separate application, but I'm not sure that having 2 applications watching these changes would co-exist properly.  Therefore, I would like to see it added to `clipmenud`.  I made a couple of attempts at adding it myself, but they ended in failure.

If you would except such a patch, I will try again, and provide a PR.

**Comment by cdown** [comment]
We already have support for primary -> clipboard: https://github.com/cdown/clipmenu/blob/develop/clipmenud#L217-L219

clipboard -> primary is more problematic: on the primary selection, clearing it usually clears the visual selection itself. That poses a problem if there is (for example) culmulative addition towards the final selection content.

**Comment by wwalker** [comment]
Thank you @cdown !

Works great!
