### ISSUE TITLE
tabs?

### ISSUE THREAD

**Issue by explosion-mental** [cdown/clipmenu#163]
on dmenu tabs are view as a box containing a cross. I think this is a dmenu 'problem', so its possible a 'solution' outside of dmenu source code. Say, we count the tabs on the clipboard text, then we eliminate them (for visualization) them we add them back (when text is selected). Wondering if clipmenu code would allow to do this and, is it even possible?

**Comment by cdown** [comment]
Hmm, why not just ask dmenu folks to add rendering, or add a patch yourself? clipmenu seems like the wrong place to do this.

**Comment by explosion-mental** [comment]
I don't plan on patching and i doubt suckless guys will patch something other than memory leaks.
What I'm asking is if you could give me some hints on scripting, is it possible at all? I only see tabs on my clipboard and would probably keep trying to get around this on my fork, but still haven't found anything yet.
Anyway thanks for the program!

**Comment by cdown** [comment]
It's certainly possible, but it requires fixing on both the producer and consumer end.

To be honest I'm not hugely against the idea of printing special characters with backslash escapes, I'll think about it.

**Comment by bdeshi** [comment]
@explosion-mental if it helps, rofi doesn't have this rendering problem with tabs

**Comment by N-R-K** [comment]
> It's certainly possible, but it requires fixing on both the producer and consumer end.
>
> To be honest I'm not hugely against the idea of printing special characters with backslash escapes, I'll think about it.

If you're thinking of simple search and replace `<TAB> => \t`, then that's going to break when the input contains a literal "\t".

Perhaps some shenanigans can be done with invalid unicode codepoints, but I think that'll just bring back the issue of those codepoints getting rendered as "boxes with cross" on dmenu, no?

**Comment by cdown** [comment]
Yeah, I don't think this will work, better to just do this on dmenu end if at all. Thanks.
