### ISSUE TITLE
[Question] In Demo, what tool for Chinese input?

### ISSUE THREAD

**Issue by ithgub** [cdown/clipmenu#164]
https://github.com/cdown/clipmenu
Demo
![Demo animation](https://cloud.githubusercontent.com/assets/660663/24079784/6f76da94-0c88-11e7-8251-40b1f02ebf3c.gif)

What is the name of the software used for typing Chinese characters?
Thank you

**Comment by cdown** [comment]
Hi! It's fcitx + sunpinyin. :-)
