### ISSUE TITLE
doesn't copy to clipboard selection if it run not from console

### ISSUE THREAD

**Issue by zordsdavini** [cdown/clipmenu#17]
I use Qtile DM and added to config to run clipmenu on keybinding. Clipmenu starts but selected text doesn't puts into clipboard. If I run it from console - all fine

**Comment by cdown** [comment]
What is the output of `env` from that environment?

**Comment by zordsdavini** [comment]
http://pastebin.com/aV3JRQPW

**Comment by cdown** [comment]
The environment is the same in both of those. How did you get the environment from the binded key?

What is the stderr/stdout of clipmenu when the failure happens? What version?

**Comment by cdown** [comment]
Or, if you've having trouble with emulating that environment, try `tr '\0' '\n' < "/proc/$(pgrep qtile)/environ" | sort` on Linux.

**Comment by zordsdavini** [comment]
It shows:
arnas@arns-arch ~> cat "/proc/1292/environ"                                     127
LC_PAPER=en_US.UTF-8XDG_VTNR=7SSH_AGENT_PID=1301LC_ADDRESS=en_US.UTF-8XDG_SESSION_ID=c1LC_MONETARY=en_US.UTF-8SHELL=/bin/zshLC_NUMERIC=en_US.UTF-8USER=arnasLC_TELEPHONE=en_US.UTF-8SSH_AUTH_SOCK=/tmp/ssh-O8fVy4ojDHVJ/agent.1300MOZ_PLUGIN_PATH=/usr/lib/mozilla/pluginsPATH=/home/arnas/.phpenv/shims:/home/arnas/.phpenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perlMAIL=/var/mail/arnasHG=/usr/bin/hgLC_IDENTIFICATION=en_US.UTF-8PWD=/home/arnasLANG=en_US.UTF-8LC_MEASUREMENT=en_US.UTF-8PAPERSIZE=letterRBENV_SHELL=bashSHLVL=0HOME=/home/arnasXDG_SEAT=seat0LANGUAGE=en_US:enLOGNAME=arnasDISPLAY=:0.0XDG_RUNTIME_DIR=/run/user/1001LC_TIME=en_US.UTF-8XAUTHORITY=/home/arnas/.XauthorityLC_NAME=en_US.UTF-8%

**Comment by cdown** [comment]
...that would be why I told you to use `tr`, to avoid that unreadable null-truncated mess.

**Comment by zordsdavini** [comment]
this was from qtile environment. Key binding is just simple:
        Key([mod], 'y', lazy.spawn('sh -c "env > /tmp/qtile_env"')),

arnas@arns-arch /tmp> cat qtile_env
XDG_VTNR=7
LC_PAPER=en_US.UTF-8
XDG_SESSION_ID=c1
LC_ADDRESS=en_US.UTF-8
SSH_AGENT_PID=1301
LC_MONETARY=en_US.UTF-8
SHELL=/bin/zsh
LC_NUMERIC=en_US.UTF-8
USER=arnas
LC_TELEPHONE=en_US.UTF-8
SSH_AUTH_SOCK=/tmp/ssh-O8fVy4ojDHVJ/agent.1300
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
MAIL=/var/mail/arnas
PATH=/home/arnas/.phpenv/shims:/home/arnas/.phpenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
HG=/usr/bin/hg
LC_IDENTIFICATION=en_US.UTF-8
PWD=/home/arnas
LANG=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
PAPERSIZE=letter
RBENV_SHELL=bash
XDG_SEAT=seat0
HOME=/home/arnas
SHLVL=1
LANGUAGE=en_US:en
LOGNAME=arnas
XDG_RUNTIME_DIR=/run/user/1001
DISPLAY=:0.0
LC_TIME=en_US.UTF-8
LC_NAME=en_US.UTF-8
XAUTHORITY=/home/arnas/.Xauthority
_=/usr/bin/env

**Comment by zordsdavini** [comment]
how can I get clipmenu errors, I don't see anything. It just not selecting into clipboard

**Comment by cdown** [comment]
You can just bind it with stdout/err going somewhere:

    Key([mod], 'y', lazy.spawn('sh -c "clipmenu >/tmp/q 2>&1"')),

**Comment by zordsdavini** [comment]
the list becomes not updating (I can't say it was updating before). 
arnas@arns-arch /tmp> cat q
/usr/bin/env/usr/bin/env% 

this was not in the list

arnas@arns-arch /tmp> type xsel xclip
xsel is /usr/bin/xsel
xclip is /usr/bin/xclip

**Comment by cdown** [comment]
If your output is "/usr/bin/env/usr/bin/env", something is very wrong with your binding itself.

**Comment by zordsdavini** [comment]
one thing. If I kill clipmenud. 
arnas@arns-arch /tmp> clipmenu
arnas@arns-arch /tmp> ps ax | grep clip
24788 ?        S      0:00 xsel --clipboard
25941 pts/5    S+     0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn clip
arnas@arns-arch /tmp> kill 24788
arnas@arns-arch /tmp> ps ax | grep clip
27592 pts/5    S+     0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn clip

what I see, that xsel is not running after key pressed

**Comment by cdown** [comment]
I have no idea what you're trying to show me in that paste. Could you please clarify?

Either way, it seems like something is wrong with your binding, judging by your previous output.

**Comment by cdown** [comment]
Closing out as no repro.
