### ISSUE TITLE
clipctl not updated in the releases since 6.1.0

### ISSUE THREAD

**Issue by PGrawe** [cdown/clipmenu#170]
Although stated in the notes in 6.1.0 (0011a2c3b981157f7decc2eac2c3db4adc04f77d) that clipctl is added (_clipctl: Add clipctl utility to temporarily disable or enable_), it wasn't actually committed to provide this functionality.
Even in 6.2.0 (7c34ace1fbab76eb1c1dc9b30dd4ac1a7fe4b90b) clipctl was not updated and only includes changes up to 9c16837227e9f90226ee7b6af1be71277389a26c.
I just wanted to ask if this is indented, because I want to use those features. Otherwise, I would just use the git version of the AUR.
Thank you.

**Comment by cdown** [comment]
I'm not sure I understand the question. In 0011a2c3b981157f7decc2eac2c3db4adc04f77d, you can see `clipctl enable` and `clipctl disable` exist with traps added in clipmenud, no?

Maybe you could rephrase what you're asking? :-)

**Comment by PGrawe** [comment]
My bad, I didn't see that. I'm sorry!
Thank you for your answer,
