### ISSUE TITLE
[FEATURE REQUEST] save some clips

### ISSUE THREAD

**Issue by foodornt** [cdown/clipmenu#175]
It would be great to have the ability to save some clips for later usage through some shortcut 🙄
I.E. Alt+S from the rofi menu to save some clip for example

**Comment by cdown** [comment]
What does "save" mean in this context? Save them where?

**Comment by foodornt** [comment]
maybe somewhere in $XDG_DATA_HOME? something like `${XDG_DATA_HOME:="$HOME/.local/share"}/clipmenu/`

**Comment by cdown** [comment]
Hmm, why does that need to be built in to clipmenu? You can already do something like:

```
CM_OUTPUT_CLIP=1 clipmenu > ${XDG_DATA_HOME:="$HOME/.local/share"}/clipmenu/whatever
```

Multi select is just waiting for a PR, #153 didn't get resubmitted after feedback.
