### ISSUE TITLE
Set the rofi prompt text

### ISSUE THREAD

**Issue by SabrinaJewson** [cdown/clipmenu#177]
Right now running clipmenu with Rofi results in the prompt text just saying `dmenu:`. But by passing in `-p clipmenu` into Rofi it will be changed to `clipmenu:` which is a lot nicer.

**Comment by cdown** [comment]
Thanks, merged 04b71fb7a9b076b88959c71760a973efe6b399c5 which passes this only for rofi, since in dmenu it takes space that otherwise wouldn't be taken.
