### ISSUE TITLE
Can't get clipmenud to start on boot in Qtile

### ISSUE THREAD

**Issue by PolSust** [cdown/clipmenu#182]
#### Fedora 35 on Qtile

I have set these 2 lines on my Qtile startup file
``` 
systemctl --user import-environment DISPLAY &
clipmenud &
```
Then when I run clipdmenu it gives me this message
```
No cache file yet, did you run clipmenud?
```

I have also tried doing the same on my .xinitrc file.

**Comment by cdown** [comment]
Hi! Did you actually select something to copy yet? We only create the cache file after the first selection is registered right now, although I suppose we could touch it on startup.

**Comment by PolSust** [comment]
It is true I hadn't copied anything yet. 

Yes the message was kinda confusing, it made me think the issue was from something more complicated than this.

Thank you for the help!
