### ISSUE TITLE
Change clipmenud to only copy things that have been ctrl +c'ed instead of just being selected

### ISSUE THREAD

**Issue by JimPix1** [cdown/clipmenu#183]
Title probably sounds confusing but clipmenud will put anything into ``line_cache`` that has been selected with the mouse but hasn't had CTRL+C been performed on it. So any selection (even accidental) gets copied to the clipboard which can be annoying. If it was only put into the clipmenu clipboard when ctrl+c occurs I think that would be better.
I've also noticed that in neovim when you copy somethings it will appear twice in the ``line_cache`` file, not a big issue as in dmenu it only shows up once.

**Comment by cdown** [comment]
That's nothing to do with clipmenu, that's just how the X `PRIMARY` clipboard works.

Use `CM_SELECTIONS=clipboard` if you don't want the primary clipboard to be managed by clipmenu.

**Comment by JimPix1** [comment]
Thanks!
