### ISSUE TITLE
[Feature request] Config/Overrides file for clipmenu

### ISSUE THREAD

**Issue by JimPix1** [cdown/clipmenu#184]
I use my own location for ``CM_DIR`` and I think it's pretty annoying to have to do ``CM_DIR=~/.local/share/clipmenu clipmenu`` to use clipmenu, clipmenud etc. etc.
I think an overrides file or a config file would be quite useful. Even some flags maybe for a custom CM_DIR location for e.g ``clipmenud -c ~/.local/share/clipmenu``.

**Comment by cdown** [comment]
I don't see why `CM_DIR=~/.local/share/clipmenu clipmenu` should be more difficult than `clipmenud -c ~/.local/share/clipmenu`.

Either way, you can:

```
alias clipmenu='CM_DIR=~/.local/share/clipmenu clipmenu'
```

Or

```
# put settings in `path'
(. path && clipmenu)
```

**Comment by cdown** [comment]
(Closed without prejudice, but I don't see any compelling reason to add it. If it turns out there is one, we can discuss further.
