### ISSUE TITLE
Status always showing 'enabled'

### ISSUE THREAD

**Issue by sarmong** [cdown/clipmenu#187]
I am using `clipmenu-git` package from AUR, and `clipctl status` command always shows `enabled`, even when clipmenu is disabled

**Comment by cdown** [comment]
Hi! Sorry to be late getting back.

This works fine for me. Maybe you can provide some more detailed repro steps?

```
clipmenu develop % ./clipctl status
enabled
clipmenu develop % ./clipctl disable
clipmenu develop % ./clipctl status 
disabled
clipmenu develop % ./clipctl enable 
clipmenu develop % ./clipctl status
enabled
```

**Comment by cdown** [comment]
Closing due to lack of information.
