### ISSUE TITLE
Unable to copy images to clipboard with Spectacle

### ISSUE THREAD

**Issue by xero-lib** [cdown/clipmenu#190]
I have spectacle set to copy screenshots to clipboard, but whenever I take a screenshot, clipmenued says `INFO: Vacuumed 1 clip files.` and I'm unaware of any way to to fix this.

**Comment by cdown** [comment]
Hi! Sorry for the late reply. Does dbb5ce9017cfce08384bbfcd18e715f28dcfde44 fix things for you?

**Comment by xero-lib** [comment]
My turn to apologize for a late reply. Unless this commit is to a different branch and not included in 6.2.0, no, I am still unable to view or copy images in clipmenu

**Comment by cdown** [comment]
Hi, yes, this is not in 6.2.0 -- please test the commit directly :)

**Comment by cdown** [comment]
Closing due to lack of information (and this is unlikely to apply to the C rewrite).
