### ISSUE TITLE
No longer working on select (rofi)

### ISSUE THREAD

**Issue by nPHYN1T3** [cdown/clipmenu#192]
I'm using with rofi v1.7.3 xsel v1.2.0. When I trigger rofi for selection it lists and I select but then the selection is never put into the clipboard. If I switch to dmenu it works. So is it rofi or clipmenu? heh

*Rofi updated to 1.7.5-1 and still broken.

**Comment by cdown** [comment]
Works fine here, so you're going to need to provide more information. For example, what does running clipmenu with xtrace show?

**Comment by nPHYN1T3** [comment]
xtrace /usr/bin/clipmenu
Function              File                                                  Line
--------------------------------------------------------------------------------
addr2line: /usr/bin/clipmenu: file format not recognized
Press return here to close xterm(/usr/bin/clipmenu). <-- after selecting from rofi list

(with dmenu selected)
xtrace /usr/bin/clipmenu
Function              File                                                  Line
--------------------------------------------------------------------------------
addr2line: /usr/bin/clipmenu: file format not recognized
addr2line: /usr/bin/clipmenu: file format not recognized
(no return to close but the selection is correctly added to clipboard)

**Comment by cdown** [comment]
`xtrace` as in `set -o xtrace`, or `set -x`.

**Comment by nPHYN1T3** [comment]
set -o xtrace
clipmenu
+ clipmenu
++ printf '\033]0;%s@%s:%s\007' $USER $HOSTNAME '~'

**Comment by cdown** [comment]
:-)

You've turned on xtract in your shell, not in clipmenu. Please run with `bash -x clipmenu`.

**Comment by nPHYN1T3** [comment]
[clipmenu.log](https://github.com/cdown/clipmenu/files/9398397/clipmenu.log)

**Comment by cdown** [comment]
Your rofi is outputting debug info on stdout (hence why the chosen line consists of 2000+ lines, which matches nothing).

Turn off `G_MESSAGES_DEBUG` or whatever you've enabled that's spamming these to stdout.
