### ISSUE TITLE
Option to not store passwords

### ISSUE THREAD

**Issue by mgpinf** [cdown/clipmenu#197]
Whenever password using pass gets copied to clipboard for a limited duration (say 45 seconds), even these get added to the clipmenu interface

**Comment by cdown** [comment]
There's already a password manager agnostic way to do that :)

```
clipctl disable
[run password manager]
clipctl enable
```

You can easily put this in a script around `pass`.

**Comment by mgpinf** [comment]
Thank you so much :)
