### ISSUE TITLE
Put new strings in clipboard from clipmenu

### ISSUE THREAD

**Issue by unclereeemus** [cdown/clipmenu#198]
Hi, I didn't want to make a PR because this seems like such an obvious thing and I am kind of surprised to find it lacking but I was able to get this functionality by changing just one line and I thought I might forward the recommendation to you in case you thought it was worthwhile or I am missing something for why it's not implemented. 

Anyway, the functionality I want is to put things in the clipboard from clipmenu. 

Here's the modification:
```
62: # [[ -f "$file" ]] || exit 2
63: [[ -f "$file" ]] || printf "$chosen_line" > "$file"
```

Further, if the search string has a match whereby if one were to press enter, the entry would be selected instead of the search string being put into the clipboard, one can just press shift+enter to instead pass the search.

**Comment by cdown** [comment]
I don't get why it would be useful. If you have to paste it somewhere, why not just write it wherever you want to write it first and then copy it?

**Comment by unclereeemus** [comment]
Well I suppose we all have our different work flows but I find this is an incredible feature as you can even edit previous selections by selecting them with tab and making your changes in the input field but if you don't feel it's integral to how your users will use the program, I am not going to push it and I'll close the issue. Thanks for the input c:
