### ISSUE TITLE
Store first line in filename to avoid lookup at runtime

### ISSUE THREAD

**Issue by cdown** [cdown/clipmenu#20]
Right now, with >5000 clips, it can get fairly slow. It might be better to just store the first line in the filename instead of the MD5, since we can uniquely identify with that too (or at least, we do anyway).

**Comment by GSI** [comment]
Chris, what do we need date & md5 for in the file names?

**Comment by cdown** [comment]
clipmenud only creates a new clip if the old one wasn't the same, so this should not have any perf changes. What are your metrics? :-)

**Comment by GSI** [comment]
In regards to ca14137: md5 calculation is a heavier operation than just outputting the current date/time.

As for the line counting (`wc -l` in fce6871), I measured it: 1.5 seconds vs. 0.9 seconds without it.

**Comment by cdown** [comment]
Right, I'm not asking you that. I'm asking you why you think this is optimising when we only use this code path when we're already in the process of creating a new clip. It's not like it runs on selection.

**Comment by cdown** [comment]
As for moving the line count to clipmenud, I don't see where you actually get the line count to display it in dmenu any more.

**Comment by GSI** [comment]
I'm still unsure what you may be referring to: Which commit? What do you mean by "code path"?

The rest will follow these days. (Note that the commit message states "not displayed yet".)

**Comment by cdown** [comment]
Partially cherry picked https://github.com/cdown/clipmenu/commit/ca1413715f297ebc7bab85239b39b270dd0ded43 to 3aa3a8d49b40277115e2474aefa1997b785013a6. Will think more about the other one.

**Comment by GSI** [comment]
Using a less common, but similar symbol like the fraction symbol seemed like a good way to handle this issue (a36658f).

**Comment by GSI** [comment]
Apart from any further bugfixes fd1b230a should close #20.

You may also want to have a look at branch **notimestamp** (eg 3259148a). It's less flexible formatting-wise, but another 30% faster than fd1b230a. Thus, personally, I'd opt for that one.

**Comment by GSI** [comment]
(Tackled the mentioned flexibility issue by formatting in the daemon. See 01b77abc for a current example.)

**Comment by cdown** [comment]
Using a similar symbol is not really an option because it's not guaranteed that the user has a font supporting this character. It's also not guaranteed to render very well, even if it does.

**Comment by GSI** [comment]
I can't help the feeling that you have yet to give the actual code a *close* look.

As for the GSI/clipmenu "20" branch the separator is never even shown.

**Comment by cdown** [comment]
Ah, I see. Yes, that looks ok to me.

Please don't use UPPER_CASE for non-environment variables, though, since it violates convention.

**Comment by cdown** [comment]
There are also a few quoting problems where `$CACHE_DIR` may be wordsplit in your commits.

**Comment by cdown** [comment]
As for sorting by datestamp -- conceptually ok, execution needs cleaning.

**Comment by cdown** [comment]
These commits are heavily interdependent, and likely some will be accepted, and some not. I can either keep on cherry picking and working them in, or feel free to submit independent ones as PRs.

**Comment by cdown** [comment]
Perf is way better in 2.0.0, and clipmenu has come a long way. Feel free to let me know if you still need this. :-)

**Comment by GSI** [comment]
I have not followed further development, since I doubt it can outperform the filename approach in speed & simplicity.

Also I have been unable to find any proof for your assumptions regarding conventions.
