### ISSUE TITLE
Why might one want to enable CM_OWN_CLIPBOARD=1?

### ISSUE THREAD

**Issue by nhooyr** [cdown/clipmenu#206]
Hi, I was wondering why one would want to enable the setting `CM_OWN_CLIPBOARD=1`?

What does it mean for `clipmenud` to take ownership of the clipboard? And why is such behaviour helpful?

I noticed it used to be default but that was changed after numerous issues with other applications that also took ownership of the clipboard.

**Comment by cdown** [comment]
> What does it mean for clipmenud to take ownership of the clipboard? And why is such behaviour helpful?

When an X application dies, it cannot serve its clipboard content. Having a long running daemon like clipmenud to serve it allows it to persist after its death.

**Comment by nhooyr** [comment]
Ah copy thanks!
