### ISSUE TITLE
I can't control it via environmental variables

### ISSUE THREAD

**Issue by Archie-2021** [cdown/clipmenu#207]
All the default values for `$CM_*` variables are empty, and when I set a value to them in my `.bashrc` it shows the value but does nothing to `clipmenu` behavior. Like I this line in my bashrc:

```
export CM_SELECTIONS="clipboard"
```

but it is still saves data from primary clipboard.

**Comment by cdown** [comment]
Then your session is not being instantiated after your bashrc is read. bashrc is not for environmental variables, so don't use it for that -- use your profile or other facilities provided by your DE.

**Comment by Archie-2021** [comment]
> Then your session is not being instantiated after your bashrc is read. bashrc is not for environmental variables, so don't use it for that -- use your profile or other facilities provided by your DE.

I also added it to the script I give my DE when initializes, but nothing happened.

**Comment by cdown** [comment]
Sorry, but I'm not going to spend time debugging your DE/distro's environment propagation -- please contact your distro support.
