### ISSUE TITLE
Unrelated question. Insert unicode in terminal.

### ISSUE THREAD

**Issue by SpatialSymmetry** [cdown/clipmenu#208]
OK I know this sounds weird, but I gotta ask. In the clipmenu introduction GIF you guys uses some kind of popup to insert Chinese characters, I was thinking about doing this. I was thinking why no one did this before til I saw this. What's the name of application? I want it for Farsi, which is rtl, does it support rtl?

**Comment by cdown** [comment]
It's fcitx with sunpinyin. Not sure if it supports Farsi.
