### ISSUE TITLE
Choosing selection no longer works

### ISSUE THREAD

**Issue by Archie-2021** [cdown/clipmenu#209]
I have systemd setting to set the value for `CM_SELECTION="clipboard"` and it was working fine. I had an update sometime ago and it stopped working, I thought it is an issue with XFCE that caused some other things to break on my system. But today I looked at `clipmenu --help` and realized this variable is no longer available. Am I missing a update note or something here? I can't find any related changed in release notes.

**Comment by cdown** [comment]
`CM_SELECTIONS`, not `CM_SELECTION`.

**Comment by Archie-2021** [comment]
> `CM_SELECTIONS`, not `CM_SELECTION`.
My bad
Yeah, it is Selections in my file. As it was working for a long time before it suddenly broke.
![image](https://github.com/cdown/clipmenu/assets/85870778/92300073-3e38-46de-a3f9-b5f53a1797d5)
