### ISSUE TITLE
[Feature Request] Add itesm to pinned / favorites list

### ISSUE THREAD

**Issue by 01101101M** [cdown/clipmenu#218]
Firstly Huge Thanks for this brilliant tool.  

Before switching to a tiling window manager  I used to manage my clipboard with this  [Gnome Extesion](https://extensions.gnome.org/extension/779/clipboard-indicator/) and now I use [Clipmenu](https://github.com/cdown/clipmenu), however, I miss the ability to pin frequently used items

### Description: 
  As a **Clipmenu** User, I would like to have a permanent favorites list.

### Feature Details:
 - Users should be able to add items to the favorites list. using the `clipfav` command.
 - Potentially we can have many lists by telling **Clipmenu** where to read/write using  `CM_FAVORITES_DIR`, `CM_DIR` env vars. 

I would love to submit an MR, and I would appreciate your thoughts/ideas on the matter.

**Comment by cdown** [comment]
Sorry, but I wouldn't accept code for this -- clipmenu has a minimal feature set and I've recieved no previous requests for this over the last 10 years.
