### ISSUE TITLE
Ignore binary selections

### ISSUE THREAD

**Issue by Pitometsu** [cdown/clipmenu#22]
Something like that broke all the history:

``` shell
$ cat ~/Pictures/star.jpg | xclip -i -selection clipboard
```

**Comment by cdown** [comment]
First of all, this isn't a "normal" way to paste binary images, you should use a [target atom](http://tronche.com/gui/x/icccm/sec-2.html#s-2.6.2) instead. If you use a target atom, this problem won't happen (clipmenu doesn't look for ones with "unusual" target atoms).

Detecting binary is not a trivial matter in bash (or, to be honest, in any language). One possibility would be to run through `file -i` and look for `text/*` and the absence of `charset=binary`, but I don't know how many false positives/negatives that may yield, and it incurs questions that I'd rather avoid (is `-i` portable? is the output of `-i` portable? etc).

Is there a reason you can't adhere to the standard and use a target atom?

**Comment by Pitometsu** [comment]
Surely I can use it, thanks for advice. But looks like it will be better to protect application from broken files which block that at all.

**Comment by cdown** [comment]
Can you show me a screenshot of the "broken" output? It looks not that bad to me when I try it.

**Comment by Pitometsu** [comment]
It just empty.

**Comment by Pitometsu** [comment]
```
clipmenu: line 35: selections[$first_line]: bad array subscript
```

**Comment by cdown** [comment]
That error message shouldn't stop you from using clipmenu, right?

**Comment by Pitometsu** [comment]
Bug in next: when some of files broken (binary), I got this error and no items in list at all.

**Comment by cdown** [comment]
Hm. That's unusual, I don't repro that.

Do you have a sample file that causes that?

**Comment by Pitometsu** [comment]
If I delete broken file by hand, it work again.

**Comment by cdown** [comment]
Whoops.

**Comment by Pitometsu** [comment]
[This one](http://i.imgur.com/s1gr83N.jpg) I use to copy in `xclip -i -selection clipboard`

**Comment by cdown** [comment]
xclip support dropped. Please reopen if this occurs with xsel.
