### ISSUE TITLE
clipmenud[371]: Error: Can't open display: :0

### ISSUE THREAD

**Issue by kaihendry** [cdown/clipmenu#23]
I noticed these sort of errors when coming out of suspend.

My workaround is a systemd service file like http://ix.io/lca

**Comment by cdown** [comment]
If you're having errors connecting to your display, they're almost certainly X server related, not clipmenud related -- ie. not a bug in clipmenu.

If you have evidence to the contrary, feel free to present it and reopen.

**Comment by cdown** [comment]
Possibly related to #25, where we can continue discussion
