### ISSUE TITLE
Allow more granual CM_IGNORE_WINDOW

### ISSUE THREAD

**Issue by h43z** [cdown/clipmenu#231]
I would like to ignore a specific website (password manager) from clipmenud for that I would need more than to ignore the window name.
This should be possible, right? As there is more information stored in window properties than the application (in this case the string firefox).

```
% xprop | grep -i firefox
WM_CLASS(STRING) = "Navigator", "firefox"
WM_ICON_NAME(COMPOUND_TEXT) = "New Issue · cdown/clipmenu — Mozilla Firefox"
_NET_WM_ICON_NAME(UTF8_STRING) = "New Issue · cdown/clipmenu — Mozilla Firefox"
WM_NAME(COMPOUND_TEXT) = "New Issue · cdown/clipmenu — Mozilla Firefox"
_NET_WM_NAME(UTF8_STRING) = "New Issue · cdown/clipmenu — Mozilla Firefox"
```

Would this be something you are willing to add to clipmenu?

**Comment by h43z** [comment]
I don't understand why clipmenu only returns the string "Firefox" and not what xprops shows me. Could it be that clipmenu does not check the type. With a bit of chatGPT (as this type of code is way out of my comfort zone) it suggested that the window name might be a XA_COMPOUND_TEXT and clipmenu does not deal with that?

**Comment by cdown** [comment]
You can use `clipctl disable` to handle this. Extending `CM_IGNORE_WINDOW` for every single prop is extremely unwieldy, sorry.

**Comment by h43z** [comment]
You can't really run `clipctl disable` automatically when you click a button on a webpage, so that sucks. Maybe I'm misunderstanding X11 here but all I want is `_NET_WM_NAME` which in theory should be what clipmenu already uses, right? But why does `xprop` (the cli tool) give a completely different value for `_NET_WM_NAME` than the `get_window_title` function in clipmenu?

**Comment by cdown** [comment]
Why do you think clipmenud sees something different? We request _NET_WM_NAME with prop UTF8_STRING.

**Comment by h43z** [comment]
Because I tested it. For this page, xprop gives me `_NET_WM_NAME(UTF8_STRING) = "New Issue · cdown/clipmenu — Mozilla Firefox"` where as if I run clipmenud (with an added `printf("Window Title: %s\n", win_title);`) and copy something on this page it only ouputs the string `Firefox`. Where did all the other stuff go?

**Comment by h43z** [comment]
Do you have an idea why this is happening?

**Comment by h43z** [comment]
Sorry bothering you but I'd love to hear back from you if possible :)

**Comment by h43z** [comment]
ping @cdown

**Comment by h43z** [comment]
I now figured out why xprop and clipmenu give me different `_NET_WM_NAME`.
Firefox uses a hidden auxiliary window that does the actual copy to the clipboard. It's not using the window that has the document.title in `WM_NAME` (like if you check with xprop and just click the firefox window). And I think it's impossible to know where the copy to clipboard originally came from.

**Comment by h43z** [comment]
I came up with a solution. Maybe this will be interesting to other people too.

It needs a custom firefox extension (or in my case I just created a ublock filter rule with a custom scriptlet) that monkey patches the native `navigator.clipboard.writeText` function to prefix it with a tag. The script will only be injected into the page context of my webapp password manager.

```
  const originalWriteText = navigator.clipboard.writeText.bind(navigator.clipboard);
  navigator.clipboard.writeText = async function(text) {
    return originalWriteText(`@remove@${text}`);
  };
```

I then use a bash script that checks with clipnotify (and xclip) if such tagged clipboard entry comes around.

```
#!/bin/bash
while clipnotify -s clipboard; do
  clipboard_selection="$(xclip -selection clipboard -o)"

  # do nothing if clipboard selection does not start with @remove@
  if [[ "$clipboard_selection" != "@remove@"* ]]; then
    continue
  fi

  # delete entry from clipmenu
  clipdel -F -d "$clipboard_selection" > /dev/null

  # transform back to actual entry
  actual_entry="${clipboard_selection/@remove@/}"

  # put the transformed entry back into clipboard selection (and therefore clipmenu)
  echo -n "$actual_entry" | xclip -selection clipboard

  # after some time remove them from clipmenu and all clipboards
  sleep 40
  clipdel -F -d "$actual_entry" > /dev/null
  clipdel -n 1 | xclip -selection primary
  clipdel -n 1 | xclip -selection clipboard
done
```
