### ISSUE TITLE
Preserve last copy in clipboard

### ISSUE THREAD

**Issue by lmccartneystar** [cdown/clipmenu#232]
Hi, I have an inconvenience and haven't found a solution yet, here's some context:
If I copy something from a window and then close it, then the clipboard is empty and I lose what I just copied.
I know I can solve this by running:
CM_OWN_CLIPBOARD=1 clipmenud
But then I also have to run clipmenu and select an entry.

Well, I find that last part inconvenient, I know I can use a keybind, but most of the time I trigger that keybind after realizing that Ive just failed to paste something because the clipboard was empty.
And since I open/close terminals all the time, this happens quite often.

It would be nice if the program would just automatically write to the clipboard what was last copied if CM_OWN_CLIPBOARD is enabled.

**Comment by lmccartneystar** [comment]
Ok, i think i just found the solution 😅, i needed to run :
CM_OWN_CLIPBOARD=1 CM_SELECTIONS="clipboard secondary" clipmenud

**Comment by furiousteabag** [comment]
Hey @lmccartneystar, does it still work for you? For me, it works a couple of times after I restart the daemon but then it stops working again (the clipboard is empty when the window from which something was copied, closes).
