### ISSUE TITLE
Core dump at the next clipping following one using the INCR protocol

### ISSUE THREAD

**Issue by vejkse** [cdown/clipmenu#241]
I’m not sure how I missed that when testing the previous time, but here is a way to reproduce it:

1. Start clipmenu with `env CM_SELECTIONS=clipboard CM_OWN_CLIPBOARD=1 CM_DEBUG=1 clipmenud`.
2. Put something in the clipboard using the INCR protocol: `printf '%.0sa' {1..4001} | xsel --clipboard`.
3. Put something else in the clipboard: `printf a | xsel --clipboard`.
4. clipmenud crashes with the following error: `free(): double free detected in tcache 2`.

If at step 2 we do `printf aa | xsel --clipboard` nothing wrong happens.

Sometimes I also get the error `double free or corruption (top)` in step 4 (maybe when there are already a few other clippings before doing step 2).

**Added:** I forgot to mention that I’m using the latest version of the develop branch.

**Comment by cdown** [comment]
Thanks! I see the problem, it's possible partial detection when the original is INCR and the new one is non-INCR.

bfbb51f1d9e4e20d0667b28da5042abf080c323f should fix it, and has a test case. Let me know how it goes :-)

**Comment by cdown** [comment]
eaf0d90381ed91400548cb6edd769c548c030cf0 is a little nicer, if you'd like to test that instead.

**Comment by vejkse** [comment]
Thank you! I just tried the branch `cdown/2024-12-14/malloc` and I couldn’t make `clipmenud` crash.

**Comment by cdown** [comment]
That's great! Thanks for testing.
