### ISSUE TITLE
Add oneshot mode to sync clipboard

### ISSUE THREAD

**Issue by kaihendry** [cdown/clipmenu#27]
When I copy from my terminal, I've noticed that sometimes the default sleep of 0.5 is not quick enough to synchronize, leaving my `clipmenu-url` to act on the wrong URL for example.

Clipmenud's loop needs to be refactored into a function so I can call clipmenu from st directly.

**Comment by cdown** [comment]
Can you show me `clipmenu-url`? I didn't find it in your dotfiles.

Your solution doesn't make much sense. It doesn't sound like you want a function, it sounds like you want a oneshot mode.

**Comment by kaihendry** [comment]
https://github.com/kaihendry/clipmenu/blob/url-shortcut/clipmenu-url

Yes, oneshot"request the clipboard manager to take over the ownership of the clipboard" as put on http://askubuntu.com/a/61328/676

**Comment by cdown** [comment]
Sounds reasonable enough.

**Comment by Link-Satonaka** [comment]
@kaihendry do I understand correctly that you are trying to launch your browser from the selected text? You're trying to take a very roundabout approach to this. The better way is to use a more direct approach with `xsel`.

`xsel -co | xargs -r xdg-open`
This prints the currently selected text to stdout, which we pipe to `xargs` so that `xdg-open` can receive it as an argument.

Replace your clipmenu-url with this single line of code :)

**Comment by kaihendry** [comment]
This is a very good suggestion, thank you! The only drawback is that I may want to use the script on the last URL after making another non-URL selection, if that makes sense?

**Comment by Link-Satonaka** [comment]
Sure. To accomplish that, I would combine your approach and mine.

Something like
```bash
#!/bin/bash

LC_COLLATE=C

if url=$(xsel -co > /tmp/sel && grep --only-matching --perl-regexp "http(s?):\/\/[^ \"\(\)\<\>\]]*" "/tmp/sel")
then
	xdg-open $url
else
	files=(/tmp/clipmenu/*)
	
	for (( i=${#files[@]}-1; i>=0; i-- )); do
		file=${files[$i]}
		if url=$(grep --only-matching --perl-regexp "http(s?):\/\/[^ \"\(\)\<\>\]]*" "$file")
		then
			xdg-open $url
			break
		fi
	done
fi
```
I have not tested this, you might have to make some adjustments.

**Comment by kaihendry** [comment]
Weird, `xsel -co` doesn't output anything for me on Arch.

**Comment by Link-Satonaka** [comment]
For the past week or so, clipmenud has not worked for me, and actively prevents me from copying anything. I've been meaning to make an issue but haven't found the time to dig into what caused this. Does `xsel -co` work for you if clipmenud is not running?

**Comment by kaihendry** [comment]
`xsel -co` is not working at all.

Reverted to using `xclip` again with

`if url=$(xclip -o | grep --only-matching --perl-regexp "http(s?):\/\/[^ \"\(\)\<\>\]]*")`

**Comment by cdown** [comment]
Easy enough now that we have locking support, see db05c51 :-)
