### ISSUE TITLE
Do not show duplicates

### ISSUE THREAD

**Issue by kaihendry** [cdown/clipmenu#30]
Sorry, I have dejavu with this. Couldn't find a past issue. Basically I want my default behaviour not to show duplicates when I open `clipmenu`. Thanks!

**Comment by cdown** [comment]
This used to be the default by virtue of the fact that we used to have the filename as only the md5 of the content, so you wouldn't get (exact) duplicates. :-)

Either way this is going to require a full scan of the directory for detection now that we don't store md5 information at all, or we can bring back the md5 calculation. Cc @GSI2016 who removed it in 05431fe6459078d, which was reasoable since we didn't use it at the time.

Probably the most performant way is to go back to storing md5 data in the filename and then scan that for duplicates.

**Comment by kaihendry** [comment]
I'd prefer md5 back. I didn't notice a performance issue.

Except that sometimes one wouldn't exactly know when the thing you have selected has made it to clipmenu of course.

Everything I copy atm is duplicated.

**Comment by biopsin** [comment]
for now I can only recommend using fdupes after v.1.51 as it's missing sort by time and inserting it at top in clipmenu.
fdupes -o time -inAdNq "/your/path/to/files" this way it should clean the list before showing results.

**Comment by kaihendry** [comment]
fdupes basically does the md5 checksumming across a series of files? https://github.com/adrianlopezroche/fdupes/

Unless I'm missing something simply bringing back https://github.com/cdown/clipmenu/commit/05431fe6459078dbc63419ba84a20f51e09107bb would be far saner?

**Comment by biopsin** [comment]
oddly I still had duplication issues prior to 05431fe, so I ended temporary using fdupes. Guess this weekend is a good time to revert 05431fe and test it again.

**Comment by Link-Satonaka** [comment]
Could you not pipe the data through `uniq` instead of using md5?

**Comment by kaihendry** [comment]
@Link-Satonaka Umm, could you show this in code? My brain is fried.

**Comment by Link-Satonaka** [comment]
https://github.com/cdown/clipmenu/blob/develop/clipmenu#L42
Change this line
`chosen_line=$(printf '%s\n' "${ordered_selections[@]}" | dmenu -l 8 "$@")`
to
`chosen_line=$(printf '%s\n' "${ordered_selections[@]}" | uniq | dmenu -l 8 "$@")`

**Comment by Link-Satonaka** [comment]
I'm not exactly sure what's going on in clipmenu's source, but I can see that the filenames for identical pastes ARE identical, save for the datestamp. My suggestion above simply ignores identical content which exists in the /tmp/clipmenu.$USER folder. IMO that's fine, but @cdown might want something that cleans up the actual duplicate files, too?

I'm not sure how well `uniq` performs on older machines, either.

**Comment by cdown** [comment]
Adjacent identical pastes are now uniquified in 3e50f94.
