### ISSUE TITLE
clipmenu "missing list" if new file is blank

### ISSUE THREAD

**Issue by biopsin** [cdown/clipmenu#31]
Hi,
I use st terminal with the "old clipboard way" patch and I noticed clipmenu would not list anymore older files in list if newest file is empty, this happens when I change window to st with mouse and sometimes dubble click inside, ops selected and copied space.
So I change **clipmenud line 40** to [[ $data == _[^[:space:]]_ ]] || continue
this solves my issue and no more accidental empty files created.

**Comment by cdown** [comment]
I don't really understand what you're suggesting here. This logic definitely doesn't sound like what's wanted:

```
$ data=''
$ [[ $data == [^[:space:]] ]]; echo $?
1
$ data='a' 
$ [[ $data == [^[:space:]] ]]; echo $?
0
$ data='ab'
$ [[ $data == [^[:space:]] ]]; echo $?
1
```

Can you give detailed reproduction steps for the issue?

**Comment by biopsin** [comment]
indeed, however I get same result substituting :space: with :blank:,
but they differ in practice,
playing around I noticed; if selection includes a line end.
So with :blank: and selecting a line with few space characters including line end, results with clip is created with only a line end -in st..(this bugs me the most as clipmenu hides older items in list).
But :space: and select few space characters with the line end results with discard, which I am leaning more on.
I'll return with a reply and also compare with today's commit:)
thanks!

**Comment by cdown** [comment]
@kaihendry also reports this, I'll look into it, but more info would be helpful :-)

**Comment by kaihendry** [comment]
http://s.natalian.org/2016-11-07/bad-array-subscript.txt

So I am not sure how a 2 line empty file is getting written.

One fix in `clipmenu` could be:

```
-    selections[$first_line]=$file
+    test "$first_line" && selections[$first_line]=$file
```

**Comment by cdown** [comment]
That still doesn't explain how this is happening, it should be stopped by two guards:

- In `clipmenud` we guard against blank pastes: https://github.com/cdown/clipmenu/blob/c5f101d996a6ef47a0ee1764bdc1ca8e16547724/clipmenud#L87-L90
- In `clipmenu` we only get the first non-blank line: https://github.com/cdown/clipmenu/blob/c5f101d996a6ef47a0ee1764bdc1ca8e16547724/clipmenu#L27

I'd be curious to know what `xxd < /tmp/clipmenu.hendry/2016-11-05-23:15:35.468072300` says.

**Comment by kaihendry** [comment]
```
~$ xxd < /tmp/clipmenu.hendry/2016-11-05-23:15:35.468072300
00000000: 0a                                       .

```

**Comment by cdown** [comment]
Oh. :-D

```
$ data=$'\n'
$ [[ $data != *[^[:blank:]]* ]]; echo $?
1
```

**Comment by cdown** [comment]
Will release 1.2.1 with this fix now.

**Comment by cdown** [comment]
Note: you will need to remove old clips that are affected by this bug. Since this is a trivial enough bug I'd rather not add extra guards to `$first_line` that would mask the issue for now.
