### ISSUE TITLE
Sometimes it just stops working

### ISSUE THREAD

**Issue by kaihendry** [cdown/clipmenu#32]
http://s.natalian.org/2016-09-28/clipmenu.mp4

Using 05431fe6459078dbc63419ba84a20f51e09107bb from the develop branch.

My [~/.config/systemd/user/clipmenud.service](http://s.natalian.org/2016-09-28/clipmenud.service)

**Comment by cdown** [comment]
e8ebe8b adds a bunch of debug logging, can you see how this looks if you run with `DEBUG=1` in the environment?

This will print a lot, so you probably want to put output in a file.

**Comment by cdown** [comment]
@kaihendry reports that this may be fixed, if I understood correctly.

**Comment by cdown** [comment]
Closing out as I believe this is fixed. It may also be related to https://github.com/cdown/clipmenu/issues/33#issuecomment-258630443

**Comment by Link-Satonaka** [comment]
I swear this was brought up as an issue last year, can't find it.

Over the past few days, my clipboard will occaisionally stop working. When I `systemctl --user status clipmenud` I see there are two clipmenud processes running.

I tried adding `LimitNPROC=1` to the service, but I've discovered that does not work with shell scripts.

For the moment I've just configured systemd to restart clipmenud.service when waking from suspend; if that doesn't work I'll open an issue.

**Comment by kaihendry** [comment]
`xclip` method still has the problem:

http://s.natalian.org/2016-11-09/stopped-working.txt

Since when I run status, the PID stays stable at 

```
27249 xclip -o -sel primary
27249 xclip -o -sel primary
```

So xclip has hanged?


A restart fixes it, but ideally we can catch that `xclip -o` has failed ?
