### ISSUE TITLE
files copy/paste stopped working

### ISSUE THREAD

**Issue by rif** [cdown/clipmenu#34]
I am using arch linux with i3 and pcmanfm. 
clipmenu 1.2.1 update broke files copy/paste. I also tried thunar and the problem persists.
If I kill clipmenud the copy/paste are working again. 
Did I miss some config option?

Thanks for the great tool!

**Comment by cdown** [comment]
Hey there!

Without being more specific, I'm not sure what issue you're reporting here. What is "files copy/paste"? Can you provide an example to repro this issue, or some video or something?

**Comment by rif** [comment]
it's just in the file manager if I hit ctrl+c  on a file and then ctrl-v nothing happens. Also if I do right-click copy then I try to do paste the paste entry is disabled (as if there is noting copied). 
Is it clearer now or do you still need a video?

**Comment by cdown** [comment]
I repro this with the following sequence:

- Copy file in pcmanfm
- `xsel -o --clipboard | xsel -i --clipboard`
- Cannot paste any more

My guess is that this also affects other atoms. As a workaround we can only take ownership of the clipboard when there's something to take ownership of.

**Comment by cdown** [comment]
2ab5b5b fixes this for my repro. Releasing as 1.2.2.

**Comment by cdown** [comment]
Released to AUR.

**Comment by rif** [comment]
works great, thanks!
