### ISSUE TITLE
Feature request: Add command line argument to specify different cache_dir

### ISSUE THREAD

**Issue by hashworks** [cdown/clipmenu#38]
Thanks for the performance upgrade!

I have a feature request: It would be great to be able to set a different `cache_dir` than `/tmp` using a command line argument. This way one could sync entries with different devices and save them on reboot.

**Comment by cdown** [comment]
Yeah sure, of course. :-)

Before I do this I probably should make the way clipmenu{,d} take settings be more reasonable, though.

**Comment by cdown** [comment]
So, this gets a bit more complicated now that we store version number in the dir name to avoid compatibility problems.

What about being able to specify a different base dir, for example, changing /tmp to ~/... instead of being able to explicitly lay out the entire path?

**Comment by hashworks** [comment]
Sounds reasonable. I don't see a problem in creating sub-dir levels.
