### ISSUE TITLE
xsel: Can't open display: (null)

### ISSUE THREAD

**Issue by kaihendry** [cdown/clipmenu#45]
https://github.com/cdown/clipmenu/blob/develop/init/clipmenud.service#L8 assumes DISPLAY=:0 but with the [new Optimus setups](https://www.archlinux.org/news/mesa-with-libglvnd-support-is-now-in-testing/) it can be on `:1`, hence `Environment=DISPLAY=:1` needs to be updated.

Not sure if this variable can be better detected.

**Comment by cdown** [comment]
This should not be autodetected, any way to do so would be flawed. If you want to use a different display, use a systemd override file: http://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services
