### ISSUE TITLE
[feature] add clipboard entry on mouse BottonRelease event rather than by polling

### ISSUE THREAD

**Issue by CDLuminate** [cdown/clipmenu#47]
> clipmenud polls the clipboard every 0.5 seconds (or another interval as configured with the CM_SLEEP environment variable). Unfortunately there's no interface to subscribe for changes in X11, so we must poll.

reference:

https://unix.stackexchange.com/questions/106736/detect-if-mouse-button-is-pressed-then-invoke-a-script-or-command

`xev -event button | grep ButtonRelease` can monitor mouse ButtonRelease event. But I don't know whether there is any pipe event listener in shell so that clipboard update could be triggered.

However the good news is that `xbindkeys` is able to bind a shell command with keyboard/mouse event.
For instance, this xbindkeys config will add a new clipboard entry on the event of left button release.
```
"add_new_entry_with_xsel"
  b:1 + Release
```

clipmenu will be way much better with this (not really tested the above yet).

**Comment by CDLuminate** [comment]
This feature will bring at least a major change to `clipmenud`. The script "add_new_entry_with_xsel“ which acts as a cache file updater and is triggered by xbindkeys, will replace the clipboard daemon. And the really daemon is then xbindkeys.

**Comment by kaihendry** [comment]
Interesting, didn't think of the mouse events. Nonetheless a generic event to trigger a copy is needed since you can make a copy without a mouse. Isn't this related to https://github.com/cdown/clipmenu/issues/27 ?

**Comment by CDLuminate** [comment]
@kaihendry Indeed. This feature requires a "one-shot" cache updater and we don't even need to trigger that in terminal because it's done on ButtonRelease. This is doable with the help of xbindkeys.

**Comment by cdown** [comment]
Mouse events are strictly tangential to copying events -- for example this will not work for me as I only use the keyboard.

We can't guess your bindings. The proper way to do this is to set your copy bindings to also do `CM_ONESHOT=1 clipmenud`, but there's no generic way to know what your copy bindings are.

**Comment by cdown** [comment]
I added a note to the readme about using `CM_ONESHOT` for this.
