### ISSUE TITLE
how to set a keybinding to use clipmenu with rofi switch?

### ISSUE THREAD

**Issue by valdoonicanlives** [cdown/clipmenu#48]
oh sorry I see it's easy to just edit the clipmenu script and change line 3 to
: "${CM_LAUNCHER=rofi}"    then the first keybinding I show below works

I use the hotkey program sxhkd and making a keybinding like
alt + y
	clipmenu
works fine but not if I try to use with rofi i.e.
alt + y
        CM_LAUNCHER=rofi clipmenu
although the above command typed in terminal works.

**Comment by cdown** [comment]
This is probably because sxhkd doesn't pass its arguments through a shell,
but does its own word splitting. I'm away from my computer, but running
with sh -c "..." may work if the tokeniser understands quotes.

**Comment by cdown** [comment]
Either way, the answer is to either

1. Invoke a shell from sxhkd, or
2. Do a one line wrapper script and invoke that instead
