### ISSUE TITLE
Optional sorting by time

### ISSUE THREAD

**Issue by cdown** [cdown/clipmenu#5]

**Comment by kaihendry** [comment]
I sort my clips by time https://github.com/kaihendry/clipmenu/commit/ba44634b2e43dae33aeb5d48815368964808fee7

**Comment by cdown** [comment]
I think using find and a temp file for this is overkill. We already control the filenames and can just sort with LC_ALL=C.

**Comment by otommod** [comment]
I think that the following would suffice:
```sh
cache_dir=/tmp/clipmenu

set -f
oldIFS=$IFS; IFS=$'\n'
for filename in $(ls -1t "$cache_dir"); do
  file="$cache_dir/$filename"
  # same loop...
done
IFS=$oldIFS
```
It can't handle files with newlines (if someone were to create one), but neither can @kaihendry 's. It also doesn't require a non-POSIX `find`.

On an unrelated note, I think that `sed -n '1{p;q}'` can be replaced with `head -1`. Is there any particular reason to use `sed` ?

**Comment by cdown** [comment]
Since even if people don't care about the time, it doesn't affect them, I think this can just be the default.

I've put up a version of clipmenu that sorts by recency on branch [feature/sort_selections](https://github.com/cdown/clipmenu/tree/feature/sort_selections). Let me know what you think @kaihendry, @otommod.

**Comment by kaihendry** [comment]
Hi Chris, been using your 3d079ab for almost a couple of weeks successfully.

I think the only issue I've seen is blank (whitespace) lines.

Also I don't quite understand your code compared to mine: https://github.com/kaihendry/clipmenu/blob/master/clipmenu#L19

I guess the `files=(/tmp/clipmenu/*)` does the sorting. Not sure what `awk '!x[$0]++'` does. A google suggests it removes duplicates. Like a `sort -u` or `sort|uniq`? ;)

Good stuff.

**Comment by cdown** [comment]
`LC_COLLATE` is the basis for the sorting. `sort -u` here is destructive -- it sorts where sorting is not asked for. The difference between the two is that the awk command does not sort, it just picks the first line that it finds to match.

**Comment by kaihendry** [comment]
If you accidentally select whitespace for example you see blank lines. No biggie.
