### ISSUE TITLE
wish: for improved security and performance, default storage to in-memory filesystem

### ISSUE THREAD

**Issue by markstos** [cdown/clipmenu#51]
Sometimes passwords and other sensitive details pass through the clipboard manager and could end up getting logged to disk through this tool, increasing the chance that they are discovered there, or potentially backed up.

This risk can be minimized while also improving performance by defaulting the cache directory to `/run/user/$uid` if it exists and is writable, and the current value of `/tmp` as a fallback. 

This directory exists as part of the `systemd` standard and is created as a `tmpfs` in-memory file system. References:
   
 * https://unix.stackexchange.com/questions/162900/what-is-this-folder-run-user-1000
 * https://wiki.archlinux.org/index.php/tmpfs
 * man file-hierarchy (on systemd-based systems)

Since `/tmp` remains a fallback, this change would be backwards compatible. The change would also pair well with [the feature to limit the clipboard history](https://github.com/cdown/clipmenu/issues/50), to avoid unbounded memory usage for clipboard storage.

**Comment by cdown** [comment]
Yeah, this is the intended use. When I originally wrote this with just the intent of using it myself (and now), I had /tmp mounted as tmpfs anyway.

That said,`tmpfs` can swap, so I wouldn't rely on this for security without encrypted swap.

It seems reasonable semantically to use /run/user though.

**Comment by cdown** [comment]
Also re: backwards compatibility, this wouldn't be backwards compatible since users may have already set `$XDG_RUNTIME_DIR`, but it wasn't previously used. Therefore their location may change implicitly during upgrade

**Comment by markstos** [comment]
I've been using Glipper, which works great, but the days of "sys tray"
applets seem numbered. On the one hand, there are "Notification Indicators"
in Ubuntu Unity, and WMs like i3 moving towards text-only interfaces.
Since I always use Glipper through a keyboard shortcut anyway, `clipmenu`
seems like a natural fit to try out as a replacement.  Thanks for sharing
it!
