### ISSUE TITLE
Wish: native Wayland support

### ISSUE THREAD

**Issue by markstos** [cdown/clipmenu#52]
It would nice to able to interact with the clipboard directly on Wayland, without the need to run XWayland to proxy traffic through an X  server. 

The Sway window manager is Wayland-native, and has already implemented a CLI to get the clipboard contents from Wayland. (Looks like `swaymsg -t get_clipboard`). Perhaps it could serve as inspiration for what's needed here. 

 * [Interact with Wayland clipboard via cli](https://github.com/swaywm/sway/issues/926)

**Comment by cdown** [comment]
I'm unlikely to implement this, I'm afraid, for a few reasons:

- Lack of desire, I personally don't run Wayland (yet) and don't need this
- Lack of people actively testing this code path
- Tying this to a particular window manager is less than ideal
- clipmenu is for X, if we're going to make one for wayland let's just make it run on native wayland

I'll close this for now, but don't let it dissuade you from filing more issues -- your recent ones have been helpful :-)

**Comment by markstos** [comment]
Looks like [clipman](https://github.com/yory8/clipman) is the same idea, but for Wayland.
