### ISSUE TITLE
Clipboard contents still apparently appears for some

### ISSUE THREAD

**Issue by cdown** [cdown/clipmenu#53]
In https://github.com/cdown/clipmenu/pull/49#issuecomment-340231013 and onwards, @markstos says that the clipboard contents is still being printed. I don't currently repro this, either running as a systemd user service or not.

**Comment by markstos** [comment]
I can confirm that this issue is resolved with the latest code on develop, on Ubuntu 17.10 with systemd 234.

Thank you.

**Comment by cdown** [comment]
Great! Thanks for all your help making clipmenu.
