### ISSUE TITLE
when clipmenud is active, can't ctrl+c and ctrl+v in MATLAB

### ISSUE THREAD

**Issue by a-0-p** [cdown/clipmenu#55]
Hi, 

loving clipmenu and have it always running in the background...I noticed that when I use MATLAB, if clipmenud is active, ctrl+c and ctrl+v won't copy and paste text. This happens for any shortcuts I set, not only for the specific combination of ctrl+c and ctrl+v. The only way I can copy and paste text is by highlighting it and then press the middle cursor on mouse...any idea why this happens, why this is specific to matlab and how to overcome this little problem?

Thanks!

**Comment by cdown** [comment]
Unfortunately MATLAB is proprietary, so I can't test with it.

It's quite likely that MATLAB is doing something strange with clipboard ownership. I would suggest testing xclip/xsel in a tight loop yourself and seeing if it has the same effect.

**Comment by a-0-p** [comment]
Ok, I'll see if I can sort this out. Thanks for the prompt response.

**Comment by cdown** [comment]
Feel free to reopen if more information is available :-)
