### ISSUE TITLE
Additional cli client for daemon

### ISSUE THREAD

**Issue by schvabodka-man** [cdown/clipmenu#56]
Hello are there any plans on implementing some simple cli interface to daemon? It would be really useful for scripting and stuff like that.

**Comment by kaihendry** [comment]
Can't you just operate on the $cache_dir ?

**Comment by schvabodka-man** [comment]
I can but seperate client is much better option

**Comment by cdown** [comment]
What kind of interfaces are you thinking about?

I agree with @kaihendry that you should just operate on the cache dir, but I think there are a few things we can do to make this easier maybe:

- Split functionality into a lib/daemon (this would also help with the current duplication of some code between clipmenu{,d})
- Programatically get the current cache_dir from clipmenud (and have it as a library function)

**Comment by schvabodka-man** [comment]
I've got clipmenud and i would like to have some unix socket and kinda API to connect to clipmenud and do some work with it.

**Comment by cdown** [comment]
What does "do some work" mean? What do you want to do?

**Comment by schvabodka-man** [comment]
For example travel through clipboard history using just some hotkeys.

**Comment by cdown** [comment]
Without clarification, I'm still really not sure what's wanted here. Feel free to clarify, and we can reopen
