### ISSUE TITLE
copy is lost when application is closed

### ISSUE THREAD

**Issue by andya9** [cdown/clipmenu#6]
If you close the application from which you copied text, you need to open clipmenu to retrieve the copied text: in other words, you can’t Ctrl-v on a new application if you have closed the one from witch you Ctrl-c.

**Comment by cdown** [comment]
Unless I'm misunderstanding your bug report, this is the normal way that the clipboard works in X Windows.

**Comment by andya9** [comment]
Yes, it is; but I don’t know how or why,  if we use something like clipit the copied text remains alive even if the application is no more.
(thanks for the quick answer by the way)

**Comment by cdown** [comment]
That's probably because clipit takes ownership of the clipboard. I don't think a clipboard manager should do that, it's too invasive.

**Comment by andya9** [comment]
Thank’you for explaining!

**Comment by cdown** [comment]
No worries. I will keep this request in mind :-)

**Comment by medwatt** [comment]
@cdown, is there any way to have this funtionality (probably optional for those of us that need it?)
