### ISSUE TITLE
fpm2 and clipnotify

### ISSUE THREAD

**Issue by biopsin** [cdown/clipmenu#61]
Hi,
I'm testing out clipnotify and it works great, but I noticed that while using [figaro's password manager](https://als.regnet.cz/fpm2/download) there is a setting to copy both user and password on enter, however while using clipnotify I'm only able to capture user but not the password, if I return to sleep it works ok. Unshure how to resolve this, any ideas?

**Comment by cdown** [comment]
Hey there!

I'm really confused by how this is supposed to work. Without clipmenud running at all, both "copy both" and "copy username/password don't seem to do anything at all. How is this fpm2 feature supposed to work?

**Comment by biopsin** [comment]
hm odd. 
Funny you should ask, I have never tested this without clipmenud, and testing it xsel only registers the username. So it seems one needs a clipboard manager to capture both. 
Looking thru the source of fpm.c it fires of the user and pass in serie, logically the password should be the last registered entry in xsel.
I will experiment patching fpm2, breaking up the way it sends to the clipboard.
