### ISSUE TITLE
Numerical sorting

### ISSUE THREAD

**Issue by p1-olm** [cdown/clipmenu#62]
Since release 5, using ``clipmenu`` to retrieve entries in most recent order is broken.
It keeps showing numeric values first (``sort -rnk1`` in ``clipmenu``).
Is it expected behaviour ?

**Comment by cdown** [comment]
I don't repro, but this sounds bad. When I copy numeric entries, they appear to be sorted by recency as expected.

**Comment by cdown** [comment]
With clipmenu on `develop`:

```
% printf a | xsel -i --primary 
% printf 1 | xsel -i --primary 
% printf b | xsel -i --primary 
% printf 2 | xsel -i --primary 
```

This seems to display correctly:

![2018-02-21_165319_901790411](https://user-images.githubusercontent.com/660663/36493598-e3e86708-1727-11e8-8c52-07f0e1d594cf.png)

Can you show a small repro?

**Comment by p1-olm** [comment]
Sure : 
```
killall clipmenud
rm -rf /var/run/user/1000/clipmenu.5.olivier/
git clone https://github.com/cdown/clipmenu
export CM_DEBUG=1
./clipmenud
printf a | xsel -i --primary 
printf 1 | xsel -i --primary 
printf b | xsel -i --primary 
printf 2 | xsel -i --primary 
```

Debug output : https://pastebin.com/C1Br9tgS
Clipmenu shows :
![test](https://user-images.githubusercontent.com/18531716/36494391-3289175e-1732-11e8-93d8-d1935cc7069b.png)

**Comment by cdown** [comment]
Can you show me `cat /var/run/user/1000/clipmenu.5.olivier/line_cache_*`?

**Comment by cdown** [comment]
Ah, I suppose if these are done within the same second, `sort` will sort them together. I can also add microsecond resolution I suppose

**Comment by cdown** [comment]
Can you try again with a93cc27? :-)

**Comment by p1-olm** [comment]
printf were not done in the same second, bug is still present with patch. Here is line_cache_*  : 
```
clipmenu (develop) ✗ cat /var/run/user/1000/clipmenu.5.olivier/line_cache_*
1519233956449586870 1519233812 cat /var/run/user/1000/clipmenu.5.olivier/line_cache_* (7 lines)
1519233956476667902 a
1519233959183856273 1
1519233961531396763 b
1519233965582047507 2
```

**Comment by cdown** [comment]
With that line cache I get the right sorting, so something is really weird here.

What's the output of this with your line cache on your system? Maybe `LC_COLLATE` is weird?

```
clipmenu develop % sort -rnk 1 < /run/user/1000/clipmenu.5.cdown/line_cache_primary
1519233965582047507 2
1519233961531396763 b
1519233959183856273 1
1519233956476667902 a
```

I should probably just set `LC_COLLATE=C` on this sort.

**Comment by cdown** [comment]
If that's the issue, 4347465 should solve it

**Comment by p1-olm** [comment]
Yes with ``LC_ALL=C`` sort is way better :)

```
 clipmenu (develop) ✗ sort -rnk 1 < /var/run/user/1000/clipmenu.5.olivier/line_cache_primary
1519233965582047507 2
1519233959183856273 1
1519233961531396763 b
1519233956476667902 a
```

```
 clipmenu (develop) ✗ LC_ALL=C sort -rnk 1 < /var/run/user/1000/clipmenu.5.olivier/line_cache_primary
1519233965582047507 2
1519233961531396763 b
1519233959183856273 1
1519233956476667902 a
```

Thanks :+1:

**Comment by cdown** [comment]
Ace! I'll release 5.0.1 now. Thanks a lot for making clipmenu better!

**Comment by cdown** [comment]
5.0.1 tagged, and released on AUR.
