### ISSUE TITLE
FATAL: $SELECTION not in cache

### ISSUE THREAD

**Issue by kaihendry** [cdown/clipmenu#70]
Hi! Thanks to your debugging tip: https://github.com/cdown/clipmenu/issues/63#issuecomment-368159598

https://s.natalian.org/2018-03-16/not-in-cache.mp4

I think I see why I am having making seemingly random selections:
```
[hendry@t480s tmp]$ bash -x "$(type -p clipmenu)"
+ : dmenu
+ : /run/user/1000
+ major_version=5
+ shopt -s nullglob
+ cache_dir=/run/user/1000/clipmenu.5.hendry
+ cache_file_prefix=/run/user/1000/clipmenu.5.hendry/line_cache
+ [[ '' == --help ]]
+ [[ '' == -h ]]
+ [[ dmenu == rofi ]]
++ LC_ALL=C
++ cat /run/user/1000/clipmenu.5.hendry/line_cache_clipboard /run/user/1000/clipmenu.5.hendry/line_cache_primary /dev/null
++ sort -rnk 1
++ cut '-d ' -f2-
++ awk '!seen[$0]++'
++ dmenu -l 8
+ chosen_line='QNAP TS-453BT3'
+ [[ -n QNAP TS-453BT3 ]]
++ cksum
+ file='/run/user/1000/clipmenu.5.hendry/2929688417 15'
+ [[ -f /run/user/1000/clipmenu.5.hendry/2929688417 15 ]]
+ printf 'FATAL: %s not in cache\n' 'QNAP TS-453BT3'
FATAL: QNAP TS-453BT3 not in cache
+ exit 2
```

I'm using the Archlinux packaged clipmenu 5.1.0-1 btw.

**Comment by cdown** [comment]
I expect something is going around deleting stuff, but I suppose it's possible there's some weird edge case.

What does `grep -R 'QNAP TS-453BT3' /run/user/1000/clipmenu.5.hendry` say?

**Comment by kaihendry** [comment]
This demonstrates the problem since I rebooted since that QNAP thing.
https://s.natalian.org/2018-03-20/clipmenu.mp4

Unfortunately my screencast was dropping some frames, so it looks a little confusing at times at what I actually selected.

**Comment by cdown** [comment]
When you encounter this, can you please grep for the backing file in `/run/user/1000/clipmenu.5.hendry`, and show me the full contents if one exists?

When this happens, what are the total number of clips present? Does clipmenud show log messages like "Removing N old clips" with debug mode on?

If it doesn't exist and you're not hitting `CM_MAX_CLIPS`, I'm fairly certain something is going around and deleting entries in `/tmp`.

**Comment by cdown** [comment]
Per e-mail, debug mode is with `CM_DEBUG=1` on.

**Comment by cdown** [comment]
Pretty sure this is the same as #73, since there's more discussion let's go there :-)
