### ISSUE TITLE
Doesn't copy into clipboard the right selection

### ISSUE THREAD

**Issue by kaihendry** [cdown/clipmenu#71]
https://s.natalian.org/2018-03-28/1522205981.mp4

Running 5.1.0-1 on Archlinux with packaged dmenu 4.8-1.

Sorry the video seems to drop frames and the initial selections are not clear.

**Comment by cdown** [comment]
I'm afraid I really don't understand what's going on here in the video. Could you be more clear? :-)

**Comment by cdown** [comment]
Pretty sure this is the same as #73, since there's more discussion let's go there :-)
