### ISSUE TITLE
Edit before pasting

### ISSUE THREAD

**Issue by stef204** [cdown/clipmenu#72]
Not sure how complex this would be (and how much extra work) but would you be open to adding a feature to modify/edit content (e.g. in default editor) before pasting?

One could bring up the clipboard, then select the clip of text and press "m" or some such to open $EDITOR, edit text, save and then go back to pasting.

Use case: when one inadvertently copies extra (blank) space with mouse which should not be there when pasting, etc.

A trim blank space function for white space before and after could do the trick as well (instead of editing) but all users may not want to trim.

The classic use case would just be to modify some of the text copied before pasting (although it probably remains an edge case?)

**Comment by cdown** [comment]
Maybe the most generic solution, instead of providing some extra functionality to clipmenu, would be to provide `clipedit` as a way to modify the contents of the current clipboard?

**Comment by stef204** [comment]
Yes, that makes a lot of sense.

**Comment by cdown** [comment]
> A default TRIM whitespace function before and after text snippet would be great though.

As it is, that's an explicit anti-goal. We try really hard to preserve the clip verbatim and it's been a key reason why many people have started to use clipmenu, see the `printf x` stuff: https://github.com/cdown/clipmenu/blob/486dbe31fa2725890a825f21b6bfbd1078a30de4/clipmenud#L148-L155

In theory this could be served by setting your $EDITOR temporarily to a sed script or similar with the proposed clipedit. I am not likely to be a user, so I'm unlikely to work on it in any urgent capacity.

**Comment by stef204** [comment]
Understood.  (And I meant as part of clipmenu not clipedit, you read it correctly in the first place)

So if I were to modify the line 155 above as such `data=${data%}` it would accomplish what I want?

**Comment by cdown** [comment]
You'd need to remove both `printf x` and `%x`. :-)

**Comment by stef204** [comment]
I want to add one more comment to illustrate my point re. trimming white spaces/blanks.
I just copied an email address on a webpage from someone and when pasting it to send him an email, it pasted like this:

`....................some.guy@somedomain.com`

GH trims the white space automatically so I had to add the [....]

This is a perfect example of why trimming _in some cases_ can be valuable.  It would make sense to have it either enabled or disabled.

Note: I still have to retry removing the `x` in both places in the code and see how it behaves though.

**Comment by cdown** [comment]
I thought about this a bit. Since this is an issue with clips in general (ie. clipmenu doesn't make it any different than the nominal case), I think the solution should almost certainly exist outside clipmenu.

One possibility is to also use clipnotify and then trim events coming off the clipboard, but I don't personally have a use case for that, I'm afraid. On that basis and on the basis that this would probably be in another repository anyway, I'm closing here, but thanks for bringing up a use case I didn't know existed prior :-)
