### ISSUE TITLE
FATAL: ... not in cache

### ISSUE THREAD

**Issue by kaihendry** [cdown/clipmenu#77]
Took longer, but same problem on 5.3.0-1.

https://s.natalian.org/2018-04-24/not-in-cache.txt

Using:

```
cat ~/.config/systemd/user/clipmenud.service.d/override.conf
[Service]
Environment=CM_DEBUG=1
Environment=CM_MAX_CLIPS=0
```

I'm still confused as to why line_cache_clipboard has it, but not '/run/user/1000/clipmenu.5.hendry/587423036 12'

I guess the cache is what dmenu renders?

**Comment by cdown** [comment]
Thanks for your patience. Yes, the cache is what dmenu renders. Can you please do `journalctl --user -u clipmenud | grep sY9DWzJnEok`?

This *shouldn't* have been deleted by possible partial detection since these two are two entries apart:

```
/run/user/1000/clipmenu.5.hendry/line_cache_primary:643:1524542807589672018 sY9DWzJnEok                                                                        
/run/user/1000/clipmenu.5.hendry/line_cache_primary:645:1524542837595481633 sY9DWzJnEok.info.json  
```

**Comment by cdown** [comment]
Also, are you sure that clipmenud was restarted after upgrade?

**Comment by cdown** [comment]
Closing due to no further info.
