### ISSUE TITLE
clipboard preservation

### ISSUE THREAD

**Issue by artebin** [cdown/clipmenu#80]
Hi cdown,
Thank you very much for clipmenu, excellent idea and code, I've never been happy with ClipIt and clipmenu is more into the suckless way.
Question: can we configure clipmenu for clipboard preservation? I mean when the process - a text editor for instance, take Geany - has exited, and the user still want to be able to paste the last filling of the clipboard made with Geany. I suppose Geany asks for a cleaning the clipboard and clipmenu would have to restore it, is it correct?
If clipmenu can not do that today, then do you know if it's a big work to add this capability to it?
NJ

**Comment by cdown** [comment]
clipmenu already does this unless you run it with `CM_OWN_CLIPBOARD=0` (1 is the default). Are you having some problem with this?

**Comment by artebin** [comment]
Ok, maybe something was wrong with my configuration parameters.
It was not working previously, I tried on 2 different machines (Xubuntu
17.04 and Xubuntu 18.04).
After reading you email I tried CM_OWN_CLIPBOARD=0, not working and it is
expected.
And then I reverted to CM_OWN_CLIPBOARD=1, now it is working.

**Comment by cdown** [comment]
Great!

**Comment by artebin** [comment]
A little addition to my previous email: it seems I have problems when using
the clipmenud.service, I think the problem is the access to the files
located in /tmp after being logged.
That said, it is not very annoying for now because anyone can start
clipmenud during session (.xsessionrc or openbox autostart in my case).

However I notice also something else and quite annoying this one: I am
using Caja (from MATE desktop) as file manager, and in this file manager
the copy/paste is not working properly when clipmenud is started: I need to
copy 2 times a file/directory (i.e. I need to type ctrl+c 2 times) for
being able to paste. Have you ever heard of a similar thing with another
file manager?
I tried Thunar and PCManFM but I do not see the same problem.

**Comment by artebin** [comment]
Ok, just found out that clipmenud process is not killed when I log out,
i.e. if I login, and then logout, login, then I can see 2 processes
clipmenud.
And I do not see the copy/paste problem at first login.
The problem is there only when multiple instances of clipmenud are running.
