### ISSUE TITLE
Systemd Unit does not work

### ISSUE THREAD

**Issue by ldenefle** [cdown/clipmenu#82]
Hi, I can't seem to start clipmenud through the systemd
The output of systemctl status clipmenud.service is : 
clipmenud[31288]: No protocol specified
clipmenud[31288]: Can't open X display
clipmenud[31288]: No protocol specified
clipmenud[31288]: xsel: Can't open display: (null)
clipmenud[31288]: : Resource temporarily unavailable

and the output of: tr '\0' '\n' < "/proc/$(pgrep -nx clipmenud)/environ" | grep '^DISPLAY='
DISPLAY=:0

This is /etc/X11/xinit/xinitrc.d/50-systemd-user.sh 
```

#!/bin/sh

systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
        dbus-update-activation-environment DISPLAY XAUTHORITY
fi
```

Do you have an idea of what could be wrong ?

Any help would be welcomed 
Thanks

**Comment by cdown** [comment]
Is your display actually at `:0`?

**Comment by ldenefle** [comment]
yes sir, 
`echo $DISPLAY`
outputs :0

**Comment by cdown** [comment]
Historically debugging X issues on GitHub has proven extremely time consuming and only revealed configuration problems, so I'm unlikely to dive too deep here, however:

1. "xsel: Can't open display: (null)" suggests that for some reason `$DISPLAY` is unset for xsel. The other errors are probably from clipnotify, I should add the program name in perror. This is probably a useful debugging angle. You can confirm this by running with `bash -x`.
2. Consider trying to run with `CM_DEBUG=1`, and seeing if that says anything useful.
3. Make sure you're starting fresh with `systemctl --user daemon-reload && systemctl restart clipmenud`.
4. Make sure you're running the latest clipmenud.
5. Make sure your X server is not detached from your user session.
6. Make sure your hostname is valid (ie. non-localhost under `hostnamectl`) or weird things will happen with X.

**Comment by ldenefle** [comment]
Thanks, I'll try that

**Comment by cdown** [comment]
Closing for now. If you find out novel information that might help others, feel free to update. Thanks.

**Comment by EgZvor** [comment]
I don't use a Desktop Environment and run i3 from `.xinitrc`, I had the same problem. My solution is to disable the service and just put `clipmenud &` inside `.xinitrc`.

**Comment by 0xMH** [comment]
For the future comers who want to run it under systemd. In order to successfully running it make sure to put `clipmenud.service` in `~/.config/systemd/user/` and then run it `systemctl --user daemon-reload && systemctl --user start clipmenud`
