### ISSUE TITLE
Not anymore on Arch User Repository

### ISSUE THREAD

**Issue by p1-olm** [cdown/clipmenu#85]
Hello,
I noticed that the AUR package (https://aur.archlinux.org/packages/clipmenu/) is not available anymore.
If I'm correct, @cdown was owner, was it done on purpose ? May I bring it back to life ?

**Comment by p1-olm** [comment]
clipnotify is gone as well

**Comment by kaihendry** [comment]
It appears to have moved to to [community]

* hhttps://www.archlinux.org/packages/community/any/clipmenu/
* https://www.archlinux.org/packages/community/x86_64/clipnotify/

Guess it's been blessed by the powers that be. Nice work Chris!

**Comment by p1-olm** [comment]
Oh ok thanks, that's great :+1: 
Good job !

**Comment by cdown** [comment]
You can thank @foxxx0 :-) Thanks Thore!
