### ISSUE TITLE
Disable recording for certain windows (e.g. password managers)

### ISSUE THREAD

**Issue by Sohalt** [cdown/clipmenu#86]
It would be cool if I could configure clipmenu to not store text copied from windows with a certain title, to avoid storing passwords copied from a password manager.
This should be fairly straightforward to implement using `xdotool getactivewindow getwindowname 
` to get the title of the currently active window and checking it against a regex before storing the clipboard.

CopyQ supports this:
https://copyq.readthedocs.io/en/latest/faq.html#how-to-omit-storing-text-copied-from-specific-windows-like-a-password-manager

**Comment by cdown** [comment]
I'd accept a patch doing this. :-)

**Comment by Sohalt** [comment]
I'll give it a go.

**Comment by Sohalt** [comment]
This is implemented in #89. Can you please have a look?
