### ISSUE TITLE
X Error of failed request

### ISSUE THREAD

**Issue by kaihendry** [cdown/clipmenu#88]
```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  178
  Current serial number in output stream:  188

```

I'm using 4.8 dmenu packaged by Archlinux, and roughly once a day I hit this issue. Any ideas?

https://s.natalian.org/2018-10-08/clipmenu.mp4

Perhaps an Emoji or something like that?

**Comment by kaihendry** [comment]
Definitely an issue with dmenu. Argh.
https://lists.suckless.org/dev/1707/31965.html

**Comment by cdown** [comment]
Just install symbola or whatever. Either way, if dmenu wants to fix this it needs to happen there
