### ISSUE TITLE
Tiny panel on Hidpi

### ISSUE THREAD

**Issue by tareefdev** [cdown/clipmenu#90]
On Hidpi screen (4k) the clipmenu seems tiny, Although I used throw Rofi which run faultlessly with `-dpi 192` parameter. Any suggestions?

**Comment by kaihendry** [comment]
Set your CM_LAUNCHER env to use rofi?

**Comment by tareefdev** [comment]
I put this: `export CM_LAUNCHER=rofi` in `.bash_profile`, isn't the right way?

**Comment by kaihendry** [comment]
Clipmenud is usually run by systemd user, hence the setting goes into `/.config/systemd/user/clipmenud.service.d/override.conf` 

```
[Service]
Environment=CM_LAUNCHER=rofi
```

**Comment by tareefdev** [comment]
I deleted that line in `.bash_profile`, and created the following file:
`~/.config/systemd/user/clipmenud.service.d/clipmenud.service.conf`:

```
[Unit]
Description=Clipmenu daemon

[Service]
ExecStart=
ExecStart=/usr/bin/clipmenud
Restart=always
RestartSec=0
Environment=DISPLAY=:0
Environment=CM_LAUNCHER=rofi

MemoryDenyWriteExecute=yes
NoNewPrivileges=yes
ProtectControlGroups=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=
RestrictRealtime=yes

[Install]
WantedBy=default.target
```

Restart my system, when I'm checking `systemctl --user status clipmenud.service` it's running but typing `printenv CM_LAUNCHER` didn't return anything.

Another trying, I execute `clipmenu -i -fn Terminus:size=22` and finally it seems great on Hidpi, but I think it's still don't use Rofi, because its colors and positions different from Rofi's settings.

Thanks.

**Comment by cdown** [comment]
> Then I restart my system, when I'm checking systemctl --user status clipmenud.service it's running but typing printenv CM_LAUNCHER didn't return anything.

That's not how environment variables work -- they're propagated by process hierarchy, `printenv` isn't going to help you here.

**Comment by tareefdev** [comment]
I found the proper way in Arch Linux wiki: "Environmental variables needed for applications should instead be added to /etc/environment", so I put there `CM_LAUNCHER=rofi` and finally clipmenu now uses rofi, and when I type `printenv CM_LAUNCHER` I got `rofi`.

Thanks.

**Comment by cdown** [comment]
> I found the proper way in Arch Linux wiki: "Environmental variables needed for applications should instead be added to /etc/environment", so I put there CM_LAUNCHER=rofi and finally clipmenu now uses rofi, and when I type printenv CM_LAUNCHER I got rofi.

This isn't really the ideal way since now this pollutes every single application you use, but if it works for you, no big deal :-)
