### ISSUE TITLE
Q: Whether does it make sense to merge clipnotify with clipmenu?

### ISSUE THREAD

**Issue by randomizedthinking** [cdown/clipmenu#99]
I would like to make a debian package for clipmenu, and feel it make sense to merge clipmenu and clipnotify together.

How do you think?

**Comment by cdown** [comment]
These are separated because clipmenu is not guaranteed to be the only consumer of clipnotify, but if a downstream distribution packages them together, that sounds fine. :-)

If that doesn't answer your question, feel free to let me know, I think there are pros and cons either way here.

**Comment by randomizedthinking** [comment]
Understood. Since clipnotify is such a small utility, better to combine
them together rather than have another dependence.

I will go ahead and create one, and have you review once it is done.
Regards.

**Comment by cdown** [comment]
I think everything is answered here, so closing -- but feel free to poke me if there's anything else :-) Thanks!
